### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by madhushreeray30** [Mr-Destructive/steampipe-plugin-cohereai#2]
Thanks @Mr-Destructive for this new plugin. Great work 🎉 !!

The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

`config/cohereai.spc`

- Could you please update the `cohereai.spc` file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
- The API key parameter should be commented out and the value should be in the format of the actual values (however incorrect).
- We also need to provide support to add the API key using the environment variable `COHERE_API_KEY`.

For instance:
```
connection "cohereai" {
  plugin = "cohereai"
  # The API key for requests. Required.
  # Get your API key at https://dashboard.cohere.ai/api-keys
  # This can also be set via the `COHERE_API_KEY` environment variable.
  # api_key = "3yA962xsa6AhjMZteFOWA7fiyAOoaFFPpWIz0aX8"
}
```

`docs/tables/*`

- The example queries in the doc look a bit light. Could you please add 2-3 more example queries wherever possible.
- Examples around JSON columns are also a good way to indicate the usage of the tables.
- The title of the queries seems to be a bit generalized and does not focus on what precisely the query is intended to do. Can we please update the titles as per the query logic?
- I believe the queries need some more formatting. Could you please update the formatting of queries using https://www.freeformatter.com/sql-formatter.html#before-output 
- Also for better formatting, I believe each query should end with the `.`period.

`docs/index.md`

- The overall structure of the `index.md` file looks correct to me
- The install section should be updated to `steampipe plugin install Mr-Destructive/cohereai` 
- Also please make sure that the [Configuration](https://github.com/Mr-Destructive/steampipe-plugin-cohereai/blob/main/docs/index.md#configuration) section is in sync with the changes suggested for the `config/cohereai.spc` file.

`README.md`

- Could you please make minor updates to follow the format mentioned in https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md
- The install section should be updated to use the `steampipe plugin install Mr-Destructive/cohereai`
- Note steps on configuring the `credentials` and `config file` should be mentioned, for reference check the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md?plain=1#L22C103-L22C103)
- Also please make sure that the [Configuration](https://github.com/Mr-Destructive/steampipe-plugin-cohereai/blob/main/README.md#configuration) section is in sync with the changes suggested for the `config/cohereai.spc` file.
- We should explicitly mention how to set the API key using the environment variable as mentioned in [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md?plain=1#L38)

`cohereai`

- I believe that the folder name should be updated to `cohereai` rather than keeping it `cohere`
- We prefer to keep the logger error as `connection_error` when there is an error returned during the client creation rather than `unmarshal_error`.
- We should display an `api_error` logger message whenever the API returns an error.
- Taking about individual tables here are a few suggestions:
  - `cohereai/table_cohereai_classify`
    - The [API](https://github.com/cohere-ai/cohere-go/blob/6462d60e9afef1f9ce34003d472ada55c3526d79/classify.go#L42) does return a few more columns then why have we focussed on adding just the `prediction` column under `classifiaction`?
    - The `input` is returned by the API itself so I guess we should not be fetching the value from the `FromQual`?
  - `cohereai/table_cohereai_embed`
    - The `embeddings` and `texts` columns should be of type `JSON` rather than `STRING`
  - `cohereai/table_cohereai_generation`
    - The [API](https://github.com/cohere-ai/cohere-go/blob/6462d60e9afef1f9ce34003d472ada55c3526d79/generate.go#L102) does return a few more columns then why have we focussed on adding just the `text` column under `generation`?
  - `cohereai/table_cohereai_summarize`
    - Is there any particular reason we are not adding the `ID` column from the API response?
  - `cohereai/table_cohereai_tokenize`
    - Is there any particular reason we are not adding the `TokenStrings` column from the API response?
  - `cohereai/connection_config`
    - Any specific reason why [this]("github.com/turbot/steampipe-plugin-sdk/v5/plugin/schema") is not imported and the var `ConfigSchema` is not set? 
  - `cohereai/plugin`
    - The plugin name should be updated to `steampipe-plugin-cohereai`
    - The table map should be sorted and properly formatted
    - The `ConnectionConfigSchema` should also include `Schema: ConfigSchema,`
  - `cohereai/utils`
    - We should add the following as it loads connection from cache, which preserves throttling protection etc:
    ```
     cacheKey := "cohereai"
	     if cachedData, ok := d.ConnectionManager.Cache.Get(cacheKey); ok {
		     return cachedData.(*coherego.Client), nil
     ``` 

A couple of follow-up questions:

Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.
While working with the APIs did you encounter rate limit errors?
Please refer https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information
Please let us know if you have questions, happy to help 👍.

**Comment by Mr-Destructive** [comment]
Ok, Thanks for the suggestions, I'll look into it and fix them.

**Comment by Mr-Destructive** [comment]
@madhushreeray30, I have addressed most of the suggestions, 

- Regarding rate limit, here's their snippet from the [pricing page](https://cohere.com/pricing)'s FAQ
> A Trial API key has a rate limit of 5000 generation units per month for the Generate and Summarize endpoints. The embed and classify endpoint are rate limited at 100 calls/minute. A Production API key has a rate limit of 10,000 calls per minute. API calls made from a Trial API key are free. API calls made from a Production API key will be charged on a pay-as-you-go basis. Trial keys are not permitted to be used for production or commercial purposes.

- There is no specification of pagination, since there is a limit to the number of generations and characters the API will respond with.
- In many of the columns, I have kept with `string` as with `json` which results in serialization errors while retrieving specifically with the `ID` fields in summary, and classify tables.

Let me know if I have missed any other details or if any further improvements can be done.
Thank you.

**Comment by madhushreeray30** [comment]
Thanks @Mr-Destructive for the quick update and fixes 🎉. The table structure and documents look good. Just a small update on the table docs, we generally do not give the API references or the `.inspect` command in the table docs as it is already available in the hub, we would encourage you to just keep the query titles followed by the query.
Please let us know if you have questions, happy to help 👍.

**Comment by Mr-Destructive** [comment]
Ok, have updated the docs. Please let me know of any other changes.
Thank you.

**Comment by madhushreeray30** [comment]
@Mr-Destructive Thanks! Could you please remove the API references from the table docs of the tables:
For instance [cohereai_classify](https://github.com/Mr-Destructive/steampipe-plugin-cohereai/blob/1cbc0a91a2d155e5aba990ebc2e21fee530f0a36/docs/tables/cohereai_detect_language.md?plain=1#L8).

**Comment by Mr-Destructive** [comment]
Ok, removed them :+1:

**Comment by madhushreeray30** [comment]
@Mr-Destructive Thanks for the updates and fixes!

**Comment by madhushreeray30** [comment]
@Mr-Destructive A quick note for the clone message in the `README.md` file, it should be `https://github.com/Mr-Destructive/steampipe-plugin-cohereai.git`, could you please update it, thanks!

**Comment by Mr-Destructive** [comment]
Thank you, have updated the link :+1:

**Comment by misraved** [comment]
@Mr-Destructive thanks once again for this great new plugin 👍 !!

The plugin is now ready for an initial release. Could you please create a release tag (`v0.0.1`) so we can publish this plugin to the hub 👍?

**Comment by Mr-Destructive** [comment]
Sure, have created the release tag :+1:
