### ISSUE TITLE
CohereAI steampipe plugin in error state unable to be used

### ISSUE THREAD

**Issue by rprahlad1** [Mr-Destructive/steampipe-plugin-cohereai#4]
Potential reason:

The plugin is installed at
~/.steampipe/plugins/hub.steampipe.io/mr-destructive/cohereai
However it is trying to find at
~/.steampipe/plugins/hub.steampipe.io/turbot/cohereai
due to the name of the plugin.

**Comment by Mr-Destructive** [comment]
Hey @misraved can you please check the name of the plugin from the hub?
It seems it is `turbot/steampipe-plugin-cohereai` instead of `mr-destructive/steampipe-plugin-cohereai`

**Comment by binaek** [comment]
@rprahlad1 @Mr-Destructive It looks like the default config file that the plugin writes has `cohereai` for the `plugin` property. 

So, `steampipe` is falling back to the `turbot` namespace. 

The value should be `mr-destructive/cohereai`

cc @misraved

**Comment by Mr-Destructive** [comment]
Thank you, I have tested locally and released the changes with [v0.0.3](https://github.com/Mr-Destructive/steampipe-plugin-cohereai/releases/tag/v0.0.3)
